# For a list of all available engines, see here:
# http://docs.codeclimate.com/article/296-engines-available-engines

engines:
# to turn on an engine, add it here and set enabled to `true`
# to turn off an engine, set enabled to `false` or remove it
  eslint:
    enabled: true
  scss-lint:
    enabled: true

ratings:
   paths:
   - src/**
   - "**.js"
