stages:
  - install
  - build
  - unit_tests
  - deploy

variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"

cache:
  key: "$CI_BUILD_REF_NAME"
  paths:
    - node_modules/

install:
  stage: install
  script:
    - npm prune
    - npm update --depth=Infinity

build:android:
  stage: build
  before_script:
    - npm install
    - npm run ionic -- cordova platform add android --no-interactive -r || echo 1
  allow_failure: true
  artifacts:
    paths:
      - "resources/android"
      - "*.apk"
  tags:
    - android
  script:
    - npm run ionic -- cordova resources android --no-interactive
    - npm run package.android 2>&1 | tee package_output.log
    - bash get_build_id.sh
    - cat packaged_number.txt
    - bash download.sh
    - ls *.apk

build:ios:
  stage: build
  tags:
    - ios
  artifacts:
    paths:
      - "resources/ios"
      - "*.ipa"
  before_script:
    - npm install
    - npm run ionic -- cordova platform add ios -r --no-interactive || echo 1
  script:
    - npm run ionic -- cordova resources ios --no-interactive
    - bash set_bundle_version.sh
    - npm run package.ios 2>&1 | tee package_output.log
    - bash get_build_id.sh
    - cat packaged_number.txt
    - bash download.sh
    - ls *.ipa

# unit_tests:
#   dependencies: []
#   stage: unit_tests
#   artifacts:
#     paths:
#       - fastlane/screenshots
#       - fastlane/logs
#   script:
#     - fastlane tests
#   tags:
#     - ios

test flight build:
  stage: deploy
  dependencies:
    - build:ios
  artifacts:
    paths:
      - fastlane/screenshots
      - fastlane/logs
  before_script:
    - gem install bundler --user-install
    - bundle install
  script:
    - fastlane pilot upload -u maistho@gmail.com
  tags:
    - ios
  only:
     - master


prod build:
  stage: deploy
  dependencies:
    - build:ios
  artifacts:
    paths:
      - fastlane/screenshots
      - fastlane/logs
  before_script:
    - gem install bundler --user-install
    - bundle install
  script:
    - fastlane pilot upload -u maistho@gmail.com
  tags:
    - ios
  only:
     - tags
