stages:
  - install
  - build
  - package
  - unit_tests
  - deploy

variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"

cache:
  key: "$CI_BUILD_REF_NAME"
  policy: pull
  paths:
    - node_modules/


install:
  stage: install
  cache:
    policy: push
  script:
    - npm install

build:
  stage: build
  artifacts:
    paths:
      - "www"
  before_script:
    - npm install
  script:
    - node scripts/set_bundle_version.js
    - npm run build
    - npm run sentry

package:android:
  stage: package
  before_script:
    - npm install
  artifacts:
    paths:
      - "resources/android"
      - "*.apk"
  tags:
    - android
  script:
    - npm run package -- android
    - ls *.apk

package:ios:
  stage: package
  tags:
    - ios
  artifacts:
    paths:
      - "resources/ios"
      - "*.ipa"
  before_script:
    - npm install
  script:
    - npm run package -- ios
    - ls *.ipa

# unit_tests:
#   dependencies: []
#   stage: unit_tests
#   artifacts:
#     paths:
#       - fastlane/screenshots
#       - fastlane/logs
#   script:
#     - fastlane tests
#   tags:
#     - ios

deploy:testflight:
  stage: deploy
  dependencies:
    - package:ios
  artifacts:
    paths:
      - fastlane/screenshots
      - fastlane/logs
  before_script:
    - gem install bundler --user-install
    - bundle install
  script:
    - fastlane pilot upload -u maistho@gmail.com
  tags:
    - ios
  only:
     - master


#deploy:appstore:
#  stage: deploy
#  dependencies:
#    - package:ios
#  artifacts:
#    paths:
#      - fastlane/screenshots
#      - fastlane/logs
#  before_script:
#    - gem install bundler --user-install
#    - bundle install
#  script:
#    - fastlane pilot upload -u maistho@gmail.com
#  tags:
#    - ios
#  only:
#     - tags
#
