options:
  formatter: stylish
files:
  include: 'src/**/*.s+(a|c)ss'
rules:
  # Extends
  extends-before-mixins: 1
  extends-before-declarations: 1
  placeholder-in-extend: 1

  # Mixins
  mixins-before-declarations: 1

  # Line Spacing
  one-declaration-per-line: 1
  empty-line-between-blocks: 1
  single-line-per-selector: 1

  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0

  # Disallows
  no-debug: 1
  no-duplicate-properties: 1
  no-mergeable-selectors: 1
  no-qualifying-elements: 0
  no-empty-rulesets: 1
  no-extends: 0
  no-ids: 0
  no-important: 1
  no-warn: 1
  no-color-keywords: 0
  no-invalid-hex: 1
  no-css-comments: 0
  no-color-literals: 0
  no-transition-all: 0

  # Style Guide
  border-zero: 1
  clean-import-paths: 1
  empty-args: 1
  hex-length: 1
  hex-notation: 1
  indentation:
    - 1
    -
      size: 4
  leading-zero: 1
  nesting-depth: 1
  property-sort-order: 0
  quotes: 0
  variable-for-property: 1
  zero-unit: 1

  # Inner Spacing
  space-after-comma: 1
  space-before-colon: 1
  space-after-colon: 1
  space-before-brace: 1
  space-before-bang: 1
  space-after-bang: 1
  space-between-parens: 1

  # Final Items
  trailing-semicolon: 1
  final-newline: 1
